/* TrailWatch HK — Shared demo data */
window.TW = window.TW || {};

TW.user = {
  name: "Alex Wong",
  nickname: "山中遊子",
  email: "alex.wong@email.com",
  avatar: "https://images.unsplash.com/photo-1551632811-561732d1e5ec?w=200&h=200&fit=crop",
  rank: "Rare Hiker Level 4",
  rankZh: "稀有行山者 等級 4",
  memberSince: 2017,
  premium: true,
  premiumEnds: "30/06/2026",
};

TW.stats = {
  records: 384,
  routes: 102,
  bookmarks: 256,
  friends: 34,
  reports: 23,
  badges: 12,
  events: 16,
  trees: 5,
  stories: 28,
  photos: 512,
  groupHikes: 36,
  distanceKm: 1234,
  climbedM: 10456,
  kcal: 142000,
  hikes: 3840,
  elevGain: 30456,
  movingHrs: 48.5,
  caloriesMcal: 13.8,
  descent: 18192,
  avgPace: "15.3",
  bestPace: "10.1",
};

TW.districts = [
  { id: "sai-kung", name: "Sai Kung", nameZh: "西貢" },
  { id: "lantau", name: "Lantau / Islands", nameZh: "大嶼山／離島" },
  { id: "hk-island", name: "Hong Kong Island", nameZh: "香港島" },
  { id: "sha-tin", name: "Sha Tin", nameZh: "沙田" },
  { id: "tai-po", name: "Tai Po", nameZh: "大埔" },
  { id: "tsuen-wan", name: "Tsuen Wan", nameZh: "荃灣" },
  { id: "north", name: "North", nameZh: "北區" },
  { id: "tuen-mun", name: "Tuen Mun", nameZh: "屯門" },
];

/** Explore trail category filters */
TW.trailFilters = [
  { id: "all", labelKey: "filter_all" },
  { id: "accessible", labelKey: "filter_accessible" },
  { id: "long", labelKey: "filter_long" },
  { id: "backyard", labelKey: "filter_backyard" },
  { id: "coastal", labelKey: "filter_coastal" },
  { id: "heritage", labelKey: "filter_heritage" },
];

TW.trails = [
  {
    id: "lantau-peak",
    title: "Lantau Peak via Sunset Peak",
    titleZh: "鳳凰山經大東山",
    district: "lantau",
    difficulty: 4,
    desc: "A rewarding hike with panoramic coastal views across Lantau Island. Perfect for golden hour.",
    descZh: "俯瞰大嶼山海景的經典路線，黃昏時段尤其壯麗。",
    distance: "7.2 km",
    duration: "2h 36m",
    elevation: "868 m",
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    tags: ["long", "coastal"],
    author: "Alex Chen",
    date: "May 11, 2024",
    monthly: "2026-07",
  },
  {
    id: "dragons-back",
    title: "Dragon's Back Ridge",
    titleZh: "龍脊",
    district: "hk-island",
    difficulty: 2,
    desc: "Hong Kong's classic coastal ridge walk with sweeping South China Sea views.",
    descZh: "香港經典海岸山脊路線，遠眺南中國海。",
    distance: "8.5 km",
    duration: "3h 10m",
    elevation: "312 m",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    tags: ["long", "coastal"],
    author: "Sarah Chen",
    date: "Apr 22, 2024",
    monthly: "2026-07",
  },
  {
    id: "tai-tam",
    title: "Tai Tam Reservoir Scenic Trail",
    titleZh: "大潭水塘郊遊徑",
    district: "hk-island",
    difficulty: 1,
    desc: "Peaceful reservoir paths through woodland with heritage dams and quiet water views.",
    descZh: "沿水塘漫步，經過歷史水壩與寧靜林徑。",
    distance: "7.2 km",
    duration: "2h 36m",
    elevation: "268 m",
    rating: 3.6,
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    tags: ["accessible", "long", "heritage", "backyard"],
    author: "David Scott",
    date: "Mar 15, 2024",
    monthly: "2026-06",
  },
  {
    id: "lung-fu-shan",
    title: "Lung Fu Shan Heritage Trail",
    titleZh: "龍虎山文物徑",
    district: "hk-island",
    difficulty: 1,
    desc: "Easy heritage walk above Central with WWII relics and city-skyline lookouts.",
    descZh: "中環上方輕鬆文物徑，途經二戰遺跡與城市景觀。",
    distance: "4.1 km",
    duration: "1h 45m",
    elevation: "145 m",
    rating: 3.8,
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=80",
    tags: ["accessible", "heritage", "backyard"],
    author: "Elena Green",
    date: "Feb 8, 2024",
    monthly: "2026-05",
  },
  {
    id: "ma-on-shan",
    title: "Ma On Shan · The Hunch Backs",
    titleZh: "馬鞍山 · 牛背脊",
    district: "sha-tin",
    difficulty: 5,
    desc: "Steep climbs to dramatic ridgelines over Sai Kung's wild country park vistas.",
    descZh: "陡峭攀升至壯麗山脊，俯瞰西貢郊野公園。",
    distance: "11.2 km",
    duration: "5h 20m",
    elevation: "780 m",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=800&q=80",
    tags: ["long"],
    author: "James Wilson",
    date: "Jan 30, 2024",
    monthly: "2026-07",
  },
  {
    id: "maclehose-4",
    title: "Maclehose Trail Section 4",
    titleZh: "麥理浩徑第四段",
    district: "sai-kung",
    difficulty: 4,
    desc: "Iconic Sai Kung section spanning beaches, ridges, and remote coastal scenery.",
    descZh: "西貢經典路段：沙灘、山脊與偏遠海岸風光。",
    distance: "12.7 km",
    duration: "4h 45m",
    elevation: "520 m",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&q=80",
    tags: ["long", "coastal"],
    author: "山中遊子",
    date: "Dec 12, 2023",
    monthly: "2026-06",
  },
  {
    id: "sunset-peak",
    title: "Sunset Peak",
    titleZh: "大東山",
    district: "lantau",
    difficulty: 3,
    desc: "Summit views that live up to the name — golden hour at its finest.",
    descZh: "名副其實的日落美景，黃金時光最佳選擇。",
    distance: "7.2 km",
    duration: "2h 36m",
    elevation: "388 m",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80",
    tags: ["long"],
    author: "Alex Wong",
    date: "May 12, 2024",
    monthly: "2026-05",
  },
  {
    id: "dogs-teeth",
    title: "Dog's Teeth Range Traverse",
    titleZh: "狗牙嶺 · 三牙全走",
    district: "sai-kung",
    difficulty: 5,
    desc: "Sharp ridgelines and technical scrambling for seasoned hikers.",
    descZh: "尖銳山脊與技術攀爬，適合資深行山者。",
    distance: "9.4 km",
    duration: "4h 10m",
    elevation: "610 m",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=800&q=80",
    tags: ["long", "coastal"],
    author: "Elena Green",
    date: "Nov 5, 2023",
    monthly: "2026-04",
  },
  {
    id: "bride-pool",
    title: "Bride's Pool Nature Trail",
    titleZh: "新娘潭自然教育徑",
    district: "tai-po",
    difficulty: 2,
    desc: "Waterfalls and woodland streams in Tai Po — great for cooler mornings.",
    descZh: "大埔瀑布與林間溪澗，適合清涼早晨。",
    distance: "5.5 km",
    duration: "2h 15m",
    elevation: "180 m",
    rating: 4.0,
    image: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&q=80",
    tags: ["accessible", "backyard"],
    author: "Maya Lin",
    date: "Oct 3, 2023",
    monthly: "2026-04",
  },
  {
    id: "needle-hill",
    title: "Needle Hill · Grassy Hill",
    titleZh: "針山 · 草山",
    district: "tsuen-wan",
    difficulty: 3,
    desc: "Classic New Territories peaks with big elevation in a compact loop.",
    descZh: "新界經典山峰，短距離高爬升。",
    distance: "8.0 km",
    duration: "3h 40m",
    elevation: "620 m",
    rating: 4.1,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    tags: ["long", "backyard"],
    author: "Ken Chan",
    date: "Sep 18, 2023",
    monthly: "2026-03",
  },
  {
    id: "patu-heng",
    title: "Pak Tam Chung to Hoi Ha",
    titleZh: "北潭涌至海下",
    district: "sai-kung",
    difficulty: 2,
    desc: "Gentle country park paths toward the marine park coastline.",
    descZh: "平緩郊野公園小徑，通往海下灣海岸。",
    distance: "10.0 km",
    duration: "3h 30m",
    elevation: "220 m",
    rating: 3.9,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    tags: ["accessible", "long", "coastal"],
    author: "Alex Chen",
    date: "Aug 2, 2023",
    monthly: "2026-03",
  },
  {
    id: "tai-mo-shan",
    title: "Tai Mo Shan Summit",
    titleZh: "大帽山山頂",
    district: "tsuen-wan",
    difficulty: 3,
    desc: "Hong Kong's highest peak — cool winds and the white weather dome.",
    descZh: "香港最高峰——涼風與白色氣象雷達球。",
    distance: "10.2 km",
    duration: "4h 20m",
    elevation: "680 m",
    rating: 4.0,
    image: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=800&q=80",
    tags: ["long"],
    author: "山中遊子",
    date: "Jul 12, 2023",
    monthly: "2026-07",
  },
];

TW.monthlyMeta = [
  { id: "2026-07", label: "July 2026", labelZh: "2026 年 7 月", current: true },
  { id: "2026-06", label: "June 2026", labelZh: "2026 年 6 月" },
  { id: "2026-05", label: "May 2026", labelZh: "2026 年 5 月" },
  { id: "2026-04", label: "April 2026", labelZh: "2026 年 4 月" },
  { id: "2026-03", label: "March 2026", labelZh: "2026 年 3 月" },
];

TW.feed = [
  {
    type: "community",
    user: "TrailWatch",
    avatar: null,
    time: "2 days ago",
    timeZh: "兩天前",
    tag: "Community",
    tagZh: "社群",
    title: "Tree Planting Day — June 8, 2024",
    titleZh: "植樹日 — 2024 年 6 月 8 日",
    body: "Join us for a countryside volunteering day across Sai Kung Country Park. All hikers welcome!",
    bodyZh: "歡迎參加西貢郊野公園義工植樹日，所有行山友均可參與！",
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&q=80",
    likes: 128,
    comments: 24,
  },
  {
    type: "story",
    user: "Sarah Chen",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    time: "5 hours ago",
    timeZh: "5 小時前",
    tag: "Story",
    tagZh: "故事",
    body: "Caught the last light over Sharp Peak. Worth every step of the ascent.",
    bodyZh: "在蚺蛇尖捕捉最後一束光線，攀升的每一步都值得。",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    likes: 86,
    comments: 12,
  },
  {
    type: "story",
    user: "山中遊子",
    avatar: "https://images.unsplash.com/photo-1551632811-561732d1e5ec?w=100&h=100&fit=crop",
    time: "Yesterday",
    timeZh: "昨天",
    tag: "Story",
    tagZh: "故事",
    body: "On Lantau Peak, the sea of clouds slowly parted.",
    bodyZh: "在鳳凰山上，雲海緩緩散開。",
    bilingual: true,
    likes: 54,
    comments: 8,
  },
  {
    type: "group",
    user: "James Wilson",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    time: "3 hours ago",
    timeZh: "3 小時前",
    tag: "Group Hike",
    tagZh: "聯誼行山",
    title: "Lantau Peak Hike",
    titleZh: "鳳凰山行山",
    body: "Weekend group hike — moderate pace, sunrise start. Spaces left!",
    bodyZh: "週末聯誼——中等步速、日出出發，尚有名額！",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e5ec?w=800&q=80",
    distance: "8.6 km",
    duration: "2:45",
    rating: 3.8,
    participants: 6,
    likes: 31,
    comments: 9,
  },
  {
    type: "record",
    user: "David Scott",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    time: "6 hours ago",
    timeZh: "6 小時前",
    tag: "Record",
    tagZh: "記錄",
    title: "Dragon's Back Trail",
    titleZh: "龍脊",
    body: "Blue sky day on the island's most famous ridge.",
    bodyZh: "藍天下行畢港島最著名山脊。",
    distance: "8.5 km",
    duration: "3:02",
    rating: 4.6,
    mapStyle: true,
    likes: 42,
    comments: 5,
  },
];

TW.records = [
  {
    title: "Sunset Peak",
    titleZh: "大東山",
    date: "May 12, 2024",
    rating: 3.6,
    snippet: "Summit views breathtaking. Challenging ascent, worth every kilometre.",
    snippetZh: "山頂景色震撼，攀升具挑戰性，絕對值得。",
    distance: "7.2 km",
    duration: "2:36",
    elev: "388 m",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=400&q=80",
  },
  {
    title: "Thousand-Column Coast",
    titleZh: "萬柱海岸",
    date: "May 8, 2024",
    rating: 4.1,
    snippet: "Dramatic hexagonal columns meeting the sea — surreal geology walk.",
    snippetZh: "六角岩柱直墜大海——夢幻地質奇景。",
    distance: "6.4 km",
    duration: "3:10",
    elev: "210 m",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80",
  },
  {
    title: "Sai Kung Ancient Trail",
    titleZh: "西貢古徑",
    date: "Apr 28, 2024",
    rating: 3.9,
    snippet: "Quiet village paths and coastal breezes on a cooler spring morning.",
    snippetZh: "春日清晨，寧靜村落小徑與海風。",
    distance: "9.1 km",
    duration: "3:45",
    elev: "290 m",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&q=80",
  },
  {
    title: "Maclehose Trail #4",
    titleZh: "麥理浩徑第四段",
    date: "Apr 14, 2024",
    rating: 4.7,
    snippet: "Long day out through Sai Kung East — beaches, ridges, and silence.",
    snippetZh: "西貢東長途日：沙灘、山脊與寂靜。",
    distance: "12.7 km",
    duration: "4:45",
    elev: "520 m",
    image: "https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=400&q=80",
  },
  {
    title: "Tai Mo Shan · Knife Edge",
    titleZh: "大帽山 · 大刀刃",
    date: "Mar 22, 2024",
    rating: 4.0,
    snippet: "Hong Kong's highest — cool wind and the white weather dome ahead.",
    snippetZh: "香港最高峰——涼風與前方白色氣象雷達球。",
    distance: "10.2 km",
    duration: "4:20",
    elev: "680 m",
    image: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=400&q=80",
  },
];

TW.reports = [
  {
    title: "Waste Dumping",
    titleZh: "非法棄置廢物",
    desc: "Garbage completely blocks access near the trail junction.",
    descZh: "垃圾完全阻塞路口附近通道。",
    status: "received",
    category: "Waste",
    date: "25/05/2026 13:59:46",
    coords: "22.285394, 114.153783",
    lat: 22.285394,
    lng: 114.153783,
    image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b4d5?w=200&q=80",
  },
  {
    title: "Fallen Tree",
    titleZh: "倒樹",
    desc: "Large tree blocking the path after recent storms.",
    descZh: "風暴後大樹阻塞路徑。",
    status: "updated",
    category: "Obstruction",
    date: "22/05/2026 09:12:03",
    coords: "22.381234, 114.268901",
    lat: 22.381234,
    lng: 114.268901,
    image: "https://images.unsplash.com/photo-1511497584788-876760111969?w=200&q=80",
  },
  {
    title: "Vandalism",
    titleZh: "破壞行為",
    desc: "Graffiti on trail signage.",
    descZh: "指示牌上的塗鴉。",
    status: "closed",
    category: "Vandalism",
    date: "18/05/2026 16:40:11",
    coords: "22.269876, 114.234567",
    lat: 22.269876,
    lng: 114.234567,
    image: "https://images.unsplash.com/photo-1569163139394-de440968e51c?w=200&q=80",
  },
];

TW.badges = [
  { name: "First Hike", nameZh: "首次行山", emoji: "🥾", color: "#2d8a45" },
  { name: "Be Friends", nameZh: "交友", emoji: "🤝", color: "#3da855" },
  { name: "To The Peak", nameZh: "登頂", emoji: "🏔️", color: "#7c3aed" },
  { name: "Trail Runner", nameZh: "越野跑", emoji: "🏃", color: "#2563eb" },
  { name: "Trail Blazer", nameZh: "開路先鋒", emoji: "🔥", color: "#dc2626" },
  { name: "Group Leader", nameZh: "隊伍領袖", emoji: "👥", color: "#9ca3af", locked: true },
];

TW.treeGame = {
  level: 7,
  xp: 1280,
  xpNext: 1500,
  streak: 5,
  challenges: [
    { id: "c1", title: "Check in at 3 tree spots", titleZh: "到訪 3 個樹點打卡", progress: 2, total: 3, xp: 80 },
    { id: "c2", title: "Share a biodiversity photo", titleZh: "分享一張生態相片", progress: 0, total: 1, xp: 40 },
    { id: "c3", title: "Week streak × 7", titleZh: "連續到訪 7 天", progress: 5, total: 7, xp: 120 },
  ],
  rewards: [
    { name: "Leaf Scout", nameZh: "葉探", emoji: "🍃" },
    { name: "Bark Reader", nameZh: "樹皮讀家", emoji: "🪵" },
    { name: "Canopy Climber", nameZh: "樹冠攀登者", emoji: "🌳" },
  ],
};

TW.meetups = [
  {
    title: "Sunrise on Sharp Peak",
    titleZh: "蚺蛇尖日出",
    date: "Sat, Jun 15 · 05:30",
    dateZh: "6 月 15 日（六）· 05:30",
    place: "Sai Kung East",
    placeZh: "西貢東",
    spots: "4",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
  },
  {
    title: "Family-Friendly Tai Tam",
    titleZh: "親子大潭行",
    date: "Sun, Jun 16 · 09:00",
    dateZh: "6 月 16 日（日）· 09:00",
    place: "HK Island",
    placeZh: "香港島",
    spots: "8",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80",
  },
  {
    title: "Lantau Peak Night Hike",
    titleZh: "鳳凰山夜行",
    date: "Fri, Jun 21 · 18:00",
    dateZh: "6 月 21 日（五）· 18:00",
    place: "Lantau",
    placeZh: "大嶼山",
    spots: "2",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=600&q=80",
  },
];

TW.hkCenter = [22.3193, 114.1694];

TW.getPlans = function () {
  try {
    return JSON.parse(localStorage.getItem("tw_plans") || "[]");
  } catch (e) {
    return [];
  }
};

TW.setPlans = function (ids) {
  localStorage.setItem("tw_plans", JSON.stringify(ids));
};

TW.togglePlan = function (trailId) {
  const plans = TW.getPlans();
  const i = plans.indexOf(trailId);
  if (i >= 0) {
    plans.splice(i, 1);
    TW.setPlans(plans);
    return false;
  }
  plans.push(trailId);
  TW.setPlans(plans);
  return true;
};

TW.isPlanned = function (trailId) {
  return TW.getPlans().indexOf(trailId) >= 0;
};

TW.districtName = function (id) {
  const d = TW.districts.find((x) => x.id === id);
  if (!d) return id;
  return TW.getLang() === "zh" ? d.nameZh : d.name;
};
