/* TrailWatch HK — Shared demo data */
window.TW = window.TW || {};

TW.user = {
  name: "Alex Wong",
  nickname: "山中遊子",
  email: "alex.wong@email.com",
  avatar: "https://images.unsplash.com/photo-1551632811-561732d1e5ec?w=200&h=200&fit=crop",
  rank: "Rare Hiker Level 4",
  rankZh: "稀有行山者 等級 4",
  memberSince: 2017,
  premium: true,
  premiumEnds: "30/06/2026",
};

TW.stats = {
  records: 384,
  routes: 18,
  bookmarks: 256,
  friends: 34,
  reports: 23,
  badges: 12,
  events: 16,
  trees: 5,
  stories: 28,
  photos: 512,
  groupHikes: 36,
  distanceKm: 1234,
  climbedM: 10456,
  kcal: 142000,
  hikes: 3840,
  elevGain: 30456,
  movingHrs: 48.5,
  caloriesMcal: 13.8,
  descent: 18192,
  avgPace: "15.3",
  bestPace: "10.1",
};

TW.districts = [
  { id: "sai-kung", name: "Sai Kung", nameZh: "西貢" },
  { id: "lantau", name: "Lantau / Islands", nameZh: "大嶼山／離島" },
  { id: "hk-island", name: "Hong Kong Island", nameZh: "香港島" },
  { id: "kowloon", name: "Kowloon", nameZh: "九龍" },
  { id: "sha-tin", name: "Sha Tin", nameZh: "沙田" },
  { id: "tai-po", name: "Tai Po", nameZh: "大埔" },
  { id: "tsuen-wan", name: "Tsuen Wan", nameZh: "荃灣" },
  { id: "north", name: "North", nameZh: "北區" },
  { id: "tuen-mun", name: "Tuen Mun", nameZh: "屯門" },
];

/** Explore trail category filters (aligned with trailwatch.hk/browse) */
TW.trailFilters = [
  { id: "all", labelKey: "filter_all" },
  { id: "accessible", labelKey: "filter_accessible" },
  { id: "long", labelKey: "filter_long" },
  { id: "backyard", labelKey: "filter_backyard" },
  { id: "coastal", labelKey: "filter_coastal" },
  { id: "heritage", labelKey: "filter_heritage" },
  { id: "nature", labelKey: "filter_nature" },
  { id: "country", labelKey: "filter_country" },
  { id: "reservoir", labelKey: "filter_reservoir" },
];

TW.trails = [
  {
    id: "lantau-trail-sections-1-12",
    sourceId: 1121559,
    title: "Lantau Trail Sections 1 & 12",
    titleZh: "鳳徑第一、十二段",
    district: "lantau",
    difficulty: 4,
    desc: "Classic Lantau Trail coastal mountain sections with sea views toward south Lantau.",
    descZh: "大嶼山鳳凰徑經典海岸山段，遠眺南大嶼海景。",
    distance: "11.96 km",
    duration: "3h 30m",
    elevation: "127 m",
    rating: 4.3,
    image: "https://www.trailwatch.hk/uploads/route-activity-photo/63703/1e2cc968-cc75-4ae0-b609-b30a35f764d7.jpg",
    tags: ["long", "coastal"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    monthly: "2026-08",
    lat: 22.240079823,
    lng: 113.957009046,
  },
  {
    id: "maclehose-trail-sections-9-10",
    sourceId: 1121518,
    title: "Maclehose Trail Sections 9 & 10",
    titleZh: "麥理浩徑第九、十段",
    district: "tsuen-wan",
    difficulty: 5,
    desc: "A long New Territories traverse linking ridgelines on the famous Maclehose Trail.",
    descZh: "麥理浩徑長途路段，沿新界山脊遠行。",
    distance: "22.41 km",
    duration: "4h 56m",
    elevation: "478 m",
    rating: 4.7,
    image: "https://www.trailwatch.hk/uploads/route-activity-photo/63703/90f2a883-1bcc-488d-b035-58cd2193b6c2.jpg",
    tags: ["long"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    monthly: "2026-08",
    lat: 22.40740369,
    lng: 114.105153143,
  },
  {
    id: "tai-long-sai-wan-ham-tin-chek-keng",
    sourceId: 1121483,
    title: "Tai Long Sai Wan · Ham Tin · Chek Keng",
    titleZh: "大浪西灣、鹹田灣、赤徑",
    district: "sai-kung",
    difficulty: 3,
    desc: "Sai Kung East beaches and coastal paths through Tai Long Wan country.",
    descZh: "西貢東大浪灣一帶沙灘與海岸徑。",
    distance: "11.56 km",
    duration: "4h 32m",
    elevation: "117 m",
    rating: 4.1,
    image: "https://www.trailwatch.hk/uploads/route-activity-track/5142/6d559428-1cdb-41a8-a1ff-bb8b68a03ccd.png",
    tags: ["long", "coastal"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    monthly: "2026-08",
    lat: 22.394848333,
    lng: 114.360201667,
  },
  {
    id: "maclehose-trail-section-1",
    sourceId: 1121477,
    title: "Maclehose Trail Section 1",
    titleZh: "麥理浩徑第一段",
    district: "sai-kung",
    difficulty: 3,
    desc: "The opening Sai Kung section of Hong Kong’s most iconic long-distance trail.",
    descZh: "香港最經典長途徑的西貢起步段。",
    distance: "9.74 km",
    duration: "2h 00m",
    elevation: "19 m",
    rating: 4.2,
    image: "https://www.trailwatch.hk/uploads/route-activity-photo/63703/0d52a7f0-0c61-42e7-98ea-1884e26fd1e9.jpg",
    tags: ["long", "coastal"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    monthly: "2026-07",
    lat: 22.397531234,
    lng: 114.319282109,
  },
  {
    id: "tung-chung-to-mui-wo",
    sourceId: 1121515,
    title: "Tung Chung to Mui Wo",
    titleZh: "東涌至梅窩",
    district: "lantau",
    difficulty: 3,
    desc: "Cross-island Lantau walk from Tung Chung toward the old ferry town of Mui Wo.",
    descZh: "由東涌橫越大嶼山前往梅窩渡輪小鎮。",
    distance: "9.81 km",
    duration: "2h 40m",
    elevation: "—",
    rating: 4.0,
    image: "https://www.trailwatch.hk/uploads/route-activity-track/91319/fd9bfe0d-f6bf-4c59-80b8-c17d0dd187e1.png",
    tags: ["long"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    monthly: "2026-07",
    lat: 22.29091234,
    lng: 113.94291883,
  },
  {
    id: "lantau-towards-fan-lau",
    sourceId: 1121595,
    title: "Lantau towards Fan Lau",
    titleZh: "大嶼山往分流",
    district: "lantau",
    difficulty: 3,
    desc: "Remote southwest Lantau coastline heading toward Fan Lau.",
    descZh: "大嶼山西南偏遠海岸，朝分流方向前進。",
    distance: "9.86 km",
    duration: "3h 14m",
    elevation: "72 m",
    rating: 4.0,
    image: "https://www.trailwatch.hk/uploads/route-activity-track/216119/eda6316d-ef73-4774-8c17-6360a860d3e4.png",
    tags: ["long", "coastal"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    monthly: "2026-07",
    lat: 22.22804997,
    lng: 113.89102321,
  },
  {
    id: "harbourfront-coastal-trail-yue-yi-ching-sha",
    sourceId: 1121517,
    title: "Harbourfront Coastal Trail · Yue Yi & Ching Sha",
    titleZh: "活力環島長廊：漁怡徑、晴沙徑",
    district: "hk-island",
    difficulty: 2,
    desc: "Hong Kong Island harbourfront segments of the Coastal Trail Challenge.",
    descZh: "港島環島徑海濱路段：漁怡徑與晴沙徑。",
    distance: "12.32 km",
    duration: "3h 38m",
    elevation: "—",
    rating: 4.1,
    image: "https://www.trailwatch.hk/uploads/route-activity-track/221904/c8924c6f-1c82-4740-bcc1-bdcda6ccba9d.png",
    tags: ["coastal", "accessible"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    monthly: "2026-06",
    lat: 22.24946456,
    lng: 114.17494336,
  },
  {
    id: "hk-island-north-harbourfront-promenade",
    sourceId: 1121476,
    title: "HK Island North Harbourfront Promenade",
    titleZh: "港島北海濱長廊",
    district: "hk-island",
    difficulty: 1,
    desc: "An easy urban waterfront stroll along Hong Kong Island’s north shore.",
    descZh: "沿港島北岸輕鬆漫步的海濱長廊。",
    distance: "11.41 km",
    duration: "2h 11m",
    elevation: "185 m",
    rating: 4.3,
    image: "https://www.trailwatch.hk/uploads/route-activity-photo/221904/1201f9b7-82d2-44f4-a221-f01e1df1cc97.jpg",
    tags: ["coastal", "accessible", "backyard"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    monthly: "2026-06",
    lat: 22.2864829,
    lng: 114.19163841,
  },
  {
    id: "aberdeen-country-park",
    sourceId: 1121484,
    title: "Aberdeen Country Park",
    titleZh: "香港仔郊野公園",
    district: "hk-island",
    difficulty: 2,
    desc: "Woodland country-park paths above Aberdeen on Hong Kong Island.",
    descZh: "港島香港仔郊野公園林間路徑。",
    distance: "8.49 km",
    duration: "4h 47m",
    elevation: "200 m",
    rating: 3.9,
    image: "https://www.trailwatch.hk/uploads/route-activity-track/135600/813017af-6082-4118-a552-b6009b406e72.png",
    tags: ["backyard", "country"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    monthly: "2026-06",
    lat: 22.257588768,
    lng: 114.193219212,
  },
  {
    id: "the-peak-garden",
    sourceId: 1121548,
    title: "The Peak Garden",
    titleZh: "山頂公園",
    district: "hk-island",
    difficulty: 1,
    desc: "A short high-elevation walk around The Peak Garden lookouts.",
    descZh: "山頂公園附近的短途高處漫步。",
    distance: "3.86 km",
    duration: "2h 32m",
    elevation: "441 m",
    rating: 3.7,
    image: "https://www.trailwatch.hk/uploads/route-activity-track/37913/ca443ae4-2a66-4550-a121-2b3b07acb7b8.png",
    tags: ["backyard", "accessible"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    monthly: "2026-05",
    lat: 22.271120651,
    lng: 114.149637166,
  },
  {
    id: "kadoorie-farm",
    sourceId: 1121565,
    title: "Kadoorie Farm",
    titleZh: "嘉道理農場",
    district: "tai-po",
    difficulty: 2,
    desc: "Nature and farm trails around Kadoorie Farm and Botanic Garden.",
    descZh: "嘉道理農場暨植物園一帶的自然路徑。",
    distance: "4.67 km",
    duration: "2h 36m",
    elevation: "158 m",
    rating: 3.7,
    image: "https://www.trailwatch.hk/uploads/route-activity-track/37913/66177da7-4e2b-435d-964c-1e20ccea20c6.png",
    tags: ["backyard", "accessible", "nature"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    monthly: "2026-05",
    lat: 22.433355195,
    lng: 114.117390728,
  },
  {
    id: "lui-kung-tin-to-ho-pui",
    sourceId: 1121564,
    title: "Lui Kung Tin to Ho Pui",
    titleZh: "雷公田至河背",
    district: "tsuen-wan",
    difficulty: 3,
    desc: "New Territories countryside link between Lui Kung Tin and Ho Pui.",
    descZh: "新界雷公田至河背的郊野路線。",
    distance: "10.4 km",
    duration: "3h 27m",
    elevation: "2 m",
    rating: 4.0,
    image: "https://www.trailwatch.hk/uploads/route-activity-track/10084/6ec58f64-dff6-4c49-8a69-7ac1e33f803b.png",
    tags: ["long", "backyard"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    lat: 22.42711741,
    lng: 114.10826588,
  },
  {
    id: "kwai-chung-kam-shan-loop",
    sourceId: 1121555,
    title: "Kwai Chung · Kam Shan Loop",
    titleZh: "葵涌金山繞一圈",
    district: "kowloon",
    difficulty: 3,
    desc: "Loop via Kam Shan Country Park paths, Shek Lei Pui Reservoir, and Shing Mun.",
    descZh: "經金山郊野公園、石梨貝水塘與城門的繞圈路線。",
    distance: "11.75 km",
    duration: "3h 26m",
    elevation: "6 m",
    rating: 4.3,
    image: "https://www.trailwatch.hk/uploads/route-activity-photo/221904/41a5ca0d-a188-4a1a-b009-813123dfa95b.jpg",
    tags: ["long", "backyard", "heritage", "reservoir", "country"],
    author: "金鷹",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    monthly: "2026-08",
    lat: 22.36355971,
    lng: 114.13154029,
  },
  {
    id: "the-twins-tai-shui-wan-half",
    sourceId: 1121485,
    title: "The Twins · Tai Shui Wan (half)",
    titleZh: "雙鹿大水敗半走",
    district: "sai-kung",
    difficulty: 4,
    desc: "Steep Sai Kung steps toward The Twins and Tai Shui Wan coastline.",
    descZh: "西貢雙鹿陡階與大水灣海岸的半日走。",
    distance: "4.59 km",
    duration: "3h 59m",
    elevation: "96 m",
    rating: 3.7,
    image: "https://www.trailwatch.hk/uploads/route-activity-track/64461/cfbaec23-0a9a-485e-9fc3-e7e32fcdad97.png",
    tags: ["long", "coastal"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    lat: 22.389668333,
    lng: 114.361616667,
  },
  {
    id: "sau-mau-ping-loop",
    sourceId: 1121543,
    title: "Sau Mau Ping Loop",
    titleZh: "秀茂坪走一圈",
    district: "kowloon",
    difficulty: 1,
    desc: "A compact backyard loop around Sau Mau Ping hillsides.",
    descZh: "秀茂坪山邊的短途後花園繞圈。",
    distance: "3.56 km",
    duration: "1h 00m",
    elevation: "73 m",
    rating: 3.7,
    image: "https://www.trailwatch.hk/uploads/route-activity-track/91319/3099cec9-79a8-4ab0-a8e7-8ff80f4b019c.png",
    tags: ["backyard", "accessible"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    lat: 22.3192142,
    lng: 114.23195429,
  },
  {
    id: "waterfront-thousand-layers",
    sourceId: 1121481,
    title: "Waterfront Thousand Layers",
    titleZh: "水畔千層",
    district: "kowloon",
    difficulty: 2,
    desc: "A rainy solo hike along layered waterfront and hillside paths.",
    descZh: "天雨獨行，沿水畔與山徑層層前進。",
    distance: "8.45 km",
    duration: "2h 30m",
    elevation: "175 m",
    rating: 4.1,
    image: "https://www.trailwatch.hk/uploads/route-activity-photo/70372/53ec84f2-645f-4895-a4dc-5f29c38f69fc.jpg",
    tags: ["backyard", "coastal"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    lat: 22.38465179,
    lng: 114.14344118,
  },
  {
    id: "morning-walk",
    sourceId: 1121550,
    title: "Morning Walk",
    titleZh: "晨間漫步",
    district: "kowloon",
    difficulty: 1,
    desc: "An easy morning community walk through urban Kowloon edges.",
    descZh: "九龍市區邊緣的輕鬆晨間步行。",
    distance: "6.1 km",
    duration: "1h 59m",
    elevation: "73 m",
    rating: 3.8,
    image: "https://www.trailwatch.hk/uploads/route-activity-track/107955/8fa5296e-384c-4729-9ef5-cd0a8a532733.png",
    tags: ["backyard", "accessible"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    lat: 22.38588456,
    lng: 114.19412682,
  },
  {
    id: "prince-edward-to-kwun-tong-pier",
    sourceId: 1121500,
    title: "Prince Edward to Kwun Tong Pier",
    titleZh: "太子至觀塘碼頭",
    district: "kowloon",
    difficulty: 2,
    desc: "Cross-Kowloon urban route from Prince Edward toward Kwun Tong Pier.",
    descZh: "由太子橫跨九龍前往觀塘碼頭的市區路線。",
    distance: "10.32 km",
    duration: "1h 56m",
    elevation: "14 m",
    rating: 4.0,
    image: "https://www.trailwatch.hk/uploads/route-activity-track/101813/e2cd7f39-22ff-42ae-85bf-63611515649d.png",
    tags: ["accessible", "coastal"],
    author: "TrailWatch community",
    date: "Aug 2026",
    sourceUrl: "https://www.trailwatch.hk/browse",
    lat: 22.32659744,
    lng: 114.168164098,
  },
];


TW.monthlyMeta = [
  { id: "2026-08", label: "August 2026", labelZh: "2026 年 8 月", current: true },
  { id: "2026-07", label: "July 2026", labelZh: "2026 年 7 月" },
  { id: "2026-06", label: "June 2026", labelZh: "2026 年 6 月" },
  { id: "2026-05", label: "May 2026", labelZh: "2026 年 5 月" },
];

TW.feed = [
  {
    type: "community",
    user: "TrailWatch",
    avatar: null,
    time: "2 days ago",
    timeZh: "兩天前",
    tag: "Community",
    tagZh: "社群",
    title: "Tree Planting Day — June 8, 2024",
    titleZh: "植樹日 — 2024 年 6 月 8 日",
    body: "Join us for a countryside volunteering day across Sai Kung Country Park. All hikers welcome!",
    bodyZh: "歡迎參加西貢郊野公園義工植樹日，所有行山友均可參與！",
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&q=80",
    likes: 128,
    comments: 24,
  },
  {
    type: "story",
    user: "Sarah Chen",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    time: "5 hours ago",
    timeZh: "5 小時前",
    tag: "Story",
    tagZh: "故事",
    body: "Caught the last light over Sharp Peak. Worth every step of the ascent.",
    bodyZh: "在蚺蛇尖捕捉最後一束光線，攀升的每一步都值得。",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    likes: 86,
    comments: 12,
  },
  {
    type: "story",
    user: "山中遊子",
    avatar: "https://images.unsplash.com/photo-1551632811-561732d1e5ec?w=100&h=100&fit=crop",
    time: "Yesterday",
    timeZh: "昨天",
    tag: "Story",
    tagZh: "故事",
    body: "On Lantau Peak, the sea of clouds slowly parted.",
    bodyZh: "在鳳凰山上，雲海緩緩散開。",
    bilingual: true,
    likes: 54,
    comments: 8,
  },
  {
    type: "group",
    user: "James Wilson",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    time: "3 hours ago",
    timeZh: "3 小時前",
    tag: "Group Hike",
    tagZh: "聯誼行山",
    title: "Lantau Peak Hike",
    titleZh: "鳳凰山行山",
    body: "Weekend group hike — moderate pace, sunrise start. Spaces left!",
    bodyZh: "週末聯誼——中等步速、日出出發，尚有名額！",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e5ec?w=800&q=80",
    distance: "8.6 km",
    duration: "2:45",
    rating: 3.8,
    participants: 6,
    likes: 31,
    comments: 9,
  },
  {
    type: "record",
    recordId: "wilson-trail-section-4",
    user: "Alex Wong",
    avatar: "https://images.unsplash.com/photo-1551632811-561732d1e5ec?w=100&h=100&fit=crop",
    time: "May 11, 2024",
    timeZh: "2024年5月11日",
    tag: "Record",
    tagZh: "記錄",
    title: "Wilson Trail Section 4",
    titleZh: "衛奕信徑第四段",
    body: "Morning section from Ngong Ping Campsite toward Fui Yiu Ha.",
    bodyZh: "清晨由昂坪營地走向灰窰下。",
    distance: "7.2 km",
    duration: "2:36",
    rating: 3.6,
    mapStyle: true,
    likes: 58,
    comments: 7,
  },
  {
    type: "record",
    recordId: "lantau-trail-1-12",
    user: "David Scott",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    time: "6 hours ago",
    timeZh: "6 小時前",
    tag: "Record",
    tagZh: "記錄",
    title: "Dragon's Back Trail",
    titleZh: "龍脊",
    body: "Blue sky day on the island's most famous ridge.",
    bodyZh: "藍天下行畢港島最著名山脊。",
    distance: "8.5 km",
    duration: "3:02",
    rating: 4.6,
    mapStyle: true,
    likes: 42,
    comments: 5,
  },
];

TW.records = [
  {
    id: "wilson-trail-section-4",
    title: "Wilson Trail Section 4",
    titleZh: "衛奕信徑第四段",
    date: "May 11, 2024",
    dateZh: "2024年5月11日",
    rating: 3.6,
    snippet: "Pat Sin Leng country paths from Ngong Ping Campsite toward Fui Yiu Ha.",
    snippetZh: "八仙嶺郊野徑，由昂坪營地走向灰窰下。",
    distance: "7.2 km",
    duration: "2:36",
    elev: "682 m",
    elevGain: 682,
    calories: 632,
    pace: "21:40 /km",
    started: "7:28 AM",
    finished: "10:04 AM",
    startedZh: "上午 7:28",
    finishedZh: "上午 10:04",
    image: "https://www.trailwatch.hk/uploads/route-activity-photo/63703/1e2cc968-cc75-4ae0-b609-b30a35f764d7.jpg",
    user: "Alex Wong",
    avatar: "https://images.unsplash.com/photo-1551632811-561732d1e5ec?w=200&h=200&fit=crop",
    groupId: "meetup_0",
    photos: [
      "assets/brand/img-hiking.jpg",
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600&q=80",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
      "assets/brand/img-route.webp",
    ],
    path: [
      [22.4825, 114.218],
      [22.485, 114.222],
      [22.488, 114.228],
      [22.491, 114.234],
      [22.494, 114.240],
      [22.497, 114.246],
      [22.500, 114.252],
    ],
  },
  {
    id: "lantau-trail-1-12",
    title: "Lantau Trail Sections 1 & 12",
    titleZh: "鳳徑第一、十二段",
    date: "Aug 4, 2026",
    dateZh: "2026年8月4日",
    rating: 4.3,
    snippet: "Coastal mountain sections on Lantau with strong sea views.",
    snippetZh: "大嶼山海岸山段，海景開闊。",
    distance: "11.96 km",
    duration: "3:30",
    elev: "127 m",
    elevGain: 127,
    calories: 780,
    pace: "17:33 /km",
    started: "7:05 AM",
    finished: "10:35 AM",
    startedZh: "上午 7:05",
    finishedZh: "上午 10:35",
    image: "https://www.trailwatch.hk/uploads/route-activity-photo/63703/1e2cc968-cc75-4ae0-b609-b30a35f764d7.jpg",
    user: "TrailWatch community",
    avatar: null,
    photos: [
      "https://www.trailwatch.hk/uploads/route-activity-photo/63703/1e2cc968-cc75-4ae0-b609-b30a35f764d7.jpg",
      "https://images.unsplash.com/photo-1551632811-561732d1e5ec?w=600&q=80",
      "assets/brand/img-hiking.jpg",
    ],
    path: [
      [22.240, 113.957],
      [22.245, 113.965],
      [22.252, 113.972],
      [22.258, 113.980],
      [22.265, 113.988],
    ],
  },
  {
    id: "maclehose-9-10",
    title: "Maclehose Trail Sections 9 & 10",
    titleZh: "麥理浩徑第九、十段",
    date: "Aug 3, 2026",
    dateZh: "2026年8月3日",
    rating: 4.7,
    snippet: "Long New Territories ridgeline day on the classic Maclehose Trail.",
    snippetZh: "麥理浩徑長途山脊日。",
    distance: "22.41 km",
    duration: "4:56",
    elev: "478 m",
    elevGain: 478,
    calories: 1240,
    pace: "13:12 /km",
    started: "6:40 AM",
    finished: "11:36 AM",
    startedZh: "上午 6:40",
    finishedZh: "上午 11:36",
    image: "https://www.trailwatch.hk/uploads/route-activity-photo/63703/90f2a883-1bcc-488d-b035-58cd2193b6c2.jpg",
    user: "TrailWatch community",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    photos: [
      "https://www.trailwatch.hk/uploads/route-activity-photo/63703/90f2a883-1bcc-488d-b035-58cd2193b6c2.jpg",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
      "assets/brand/img-route.webp",
    ],
    path: [
      [22.407, 114.105],
      [22.410, 114.115],
      [22.415, 114.125],
      [22.420, 114.135],
      [22.425, 114.145],
    ],
  },
  {
    id: "tai-long-sai-wan",
    title: "Tai Long Sai Wan · Ham Tin · Chek Keng",
    titleZh: "大浪西灣、鹹田灣、赤徑",
    date: "Aug 2, 2026",
    dateZh: "2026年8月2日",
    rating: 4.1,
    snippet: "Sai Kung East beaches and quiet coastal paths.",
    snippetZh: "西貢東沙灘與寧靜海岸徑。",
    distance: "11.56 km",
    duration: "4:32",
    elev: "117 m",
    elevGain: 117,
    calories: 690,
    pace: "23:32 /km",
    started: "8:10 AM",
    finished: "12:42 PM",
    startedZh: "上午 8:10",
    finishedZh: "下午 12:42",
    image: "https://www.trailwatch.hk/uploads/route-activity-track/5142/6d559428-1cdb-41a8-a1ff-bb8b68a03ccd.png",
    user: "Sarah Chen",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    photos: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600&q=80",
      "assets/brand/img-hiking.jpg",
    ],
    path: [
      [22.395, 114.360],
      [22.398, 114.365],
      [22.402, 114.370],
      [22.406, 114.375],
      [22.410, 114.380],
    ],
  },
  {
    id: "harbourfront-coastal",
    title: "Harbourfront Coastal Trail · Yue Yi & Ching Sha",
    titleZh: "活力環島長廊：漁怡徑、晴沙徑",
    date: "Aug 3, 2026",
    dateZh: "2026年8月3日",
    rating: 4.0,
    snippet: "Hong Kong Island harbourfront segments of the Coastal Trail Challenge.",
    snippetZh: "港島環島徑海濱路段。",
    distance: "12.32 km",
    duration: "3:38",
    elev: "—",
    elevGain: 42,
    calories: 540,
    pace: "17:42 /km",
    started: "9:00 AM",
    finished: "12:38 PM",
    startedZh: "上午 9:00",
    finishedZh: "下午 12:38",
    image: "https://www.trailwatch.hk/uploads/route-activity-track/221904/c8924c6f-1c82-4740-bcc1-bdcda6ccba9d.png",
    user: "TrailWatch community",
    avatar: null,
    photos: [
      "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=600&q=80",
      "assets/brand/img-route.webp",
    ],
    path: [
      [22.285, 114.155],
      [22.288, 114.165],
      [22.291, 114.175],
      [22.294, 114.185],
    ],
  },
  {
    id: "kwai-chung-kam-shan",
    title: "Kwai Chung · Kam Shan Loop",
    titleZh: "葵涌金山繞一圈",
    date: "Aug 4, 2026",
    dateZh: "2026年8月4日",
    rating: 4.2,
    snippet: "Kam Shan country paths, reservoir edges, and Shing Mun.",
    snippetZh: "金山郊野徑、水塘邊與城門。",
    distance: "11.75 km",
    duration: "3:26",
    elev: "6 m",
    elevGain: 186,
    calories: 610,
    pace: "17:32 /km",
    started: "7:45 AM",
    finished: "11:11 AM",
    startedZh: "上午 7:45",
    finishedZh: "上午 11:11",
    image: "https://www.trailwatch.hk/uploads/route-activity-photo/221904/41a5ca0d-a188-4a1a-b009-813123dfa95b.jpg",
    user: "金鷹",
    avatar: null,
    photos: [
      "https://www.trailwatch.hk/uploads/route-activity-photo/221904/41a5ca0d-a188-4a1a-b009-813123dfa95b.jpg",
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80",
      "assets/brand/img-hiking.jpg",
    ],
    path: [
      [22.370, 114.140],
      [22.375, 114.148],
      [22.380, 114.155],
      [22.385, 114.162],
    ],
  },
];

TW.reports = [
  {
    title: "Waste Dumping",
    titleZh: "非法棄置廢物",
    desc: "Garbage completely blocks access near the trail junction.",
    descZh: "垃圾完全阻塞路口附近通道。",
    status: "received",
    category: "Waste",
    date: "25/05/2026 13:59:46",
    coords: "22.285394, 114.153783",
    lat: 22.285394,
    lng: 114.153783,
    image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b4d5?w=200&q=80",
  },
  {
    title: "Fallen Tree",
    titleZh: "倒樹",
    desc: "Large tree blocking the path after recent storms.",
    descZh: "風暴後大樹阻塞路徑。",
    status: "updated",
    category: "Obstruction",
    date: "22/05/2026 09:12:03",
    coords: "22.381234, 114.268901",
    lat: 22.381234,
    lng: 114.268901,
    image: "https://images.unsplash.com/photo-1511497584788-876760111969?w=200&q=80",
  },
  {
    title: "Vandalism",
    titleZh: "破壞行為",
    desc: "Graffiti on trail signage.",
    descZh: "指示牌上的塗鴉。",
    status: "closed",
    category: "Vandalism",
    date: "18/05/2026 16:40:11",
    coords: "22.269876, 114.234567",
    lat: 22.269876,
    lng: 114.234567,
    image: "https://images.unsplash.com/photo-1569163139394-de440968e51c?w=200&q=80",
  },
];

TW.badges = [
  { name: "First Hike", nameZh: "首次行山", emoji: "🥾", color: "#2d8a45" },
  { name: "Be Friends", nameZh: "交友", emoji: "🤝", color: "#3da855" },
  { name: "To The Peak", nameZh: "登頂", emoji: "🏔️", color: "#7c3aed" },
  { name: "Trail Runner", nameZh: "越野跑", emoji: "🏃", color: "#2563eb" },
  { name: "Trail Blazer", nameZh: "開路先鋒", emoji: "🔥", color: "#dc2626" },
  { name: "Group Leader", nameZh: "隊伍領袖", emoji: "👥", color: "#9ca3af", locked: true },
];

TW.treeGame = {
  level: 7,
  xp: 1280,
  xpNext: 1500,
  streak: 5,
  challenges: [
    { id: "c1", title: "Check in at 3 tree spots", titleZh: "到訪 3 個樹點打卡", progress: 2, total: 3, xp: 80 },
    { id: "c2", title: "Share a biodiversity photo", titleZh: "分享一張生態相片", progress: 0, total: 1, xp: 40 },
    { id: "c3", title: "Week streak × 7", titleZh: "連續到訪 7 天", progress: 5, total: 7, xp: 120 },
  ],
  rewards: [
    { name: "Leaf Scout", nameZh: "葉探", emoji: "🍃" },
    { name: "Bark Reader", nameZh: "樹皮讀家", emoji: "🪵" },
    { name: "Canopy Climber", nameZh: "樹冠攀登者", emoji: "🌳" },
  ],
};

TW.meetups = [
  {
    title: "Sunrise on Sharp Peak",
    titleZh: "蚺蛇尖日出",
    date: "Sat, Jun 15 · 05:30",
    dateZh: "6 月 15 日（六）· 05:30",
    place: "Sai Kung East",
    placeZh: "西貢東",
    spots: "4",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
  },
  {
    title: "Family-Friendly Tai Tam",
    titleZh: "親子大潭行",
    date: "Sun, Jun 16 · 09:00",
    dateZh: "6 月 16 日（日）· 09:00",
    place: "HK Island",
    placeZh: "香港島",
    spots: "8",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80",
  },
  {
    title: "Lantau Peak Night Hike",
    titleZh: "鳳凰山夜行",
    date: "Fri, Jun 21 · 18:00",
    dateZh: "6 月 21 日（五）· 18:00",
    place: "Lantau",
    placeZh: "大嶼山",
    spots: "2",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=600&q=80",
  },
];


/** Articles from blog.trailwatch.hk (WordPress REST API) */
TW.articleCategories = [
  { id: "all", labelKey: "article_cat_all" },
  { id: "blog", labelKey: "article_cat_blog" },
  { id: "features", labelKey: "article_cat_features" },
  { id: "hiking-tips", labelKey: "article_cat_hiking_tips" },
  { id: "activity-review", labelKey: "article_cat_activity_review" },
  { id: "whats-new", labelKey: "article_cat_whats_new" },
];

TW.articles = [
  {
    id: "blog-8780",
    sourceId: 8780,
    category: "features",
    featured: true,
    title: "Japanese YouTuber Kato Masahiko on Navigating Hong Kong Trails Like a Local",
    titleZh: "【老外眼中的香港郊野】專訪「MASAまさ千里走」YouTube版主加藤雅彥 拍地道跑山片配廣東話",
    excerpt: "Text: Teddy LAW（Parks and Trails） Photography: Kato Masahiko（MASAまさ千里走） Mr Kato Masahiko’s first impression of Hong Kong was of “a city full of energy”. While gazing up at the towering International Finance Centre, he couldn’t help but dream about establishing his own company. On",
    excerptZh: "文：Teddy LAW（Parks and Trails） 圖：加藤雅彥（MASAまさ千里走） 「活力之城」是他對香港的第一印象。仰望著參天的國際金融中心，他曾憧憬在此創辦一家公司。一年後，他果真實現了這個夢想。 來自日本的加藤雅彥先生，自2005年起不時往返港日兩地工作，直至2018年開始定居香港。加藤不但是一名金融顧問與投資者，也是一名Youtuber。然而，這個影音平台的內容非關投資，而是跑山和跑步的專屬頻道。兩年多前，加藤因看到日本YouTuber一段關於長距離越野跑影片而深受感動，決定開設「MASAまさ千里走」頻道，至今吸引逾3,500人追蹤，",
    date: "2026-07-30",
    author: "bonnie",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/07/cover-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/8780",
    urlZh: "https://blog.trailwatch.hk/zh/archives/8778",
    tags: [{ id: "interview", name: "interview", nameZh: "專訪" }, { id: "trail-running", name: "trail running", nameZh: "越野跑" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-8773",
    sourceId: 8773,
    category: "features",
    featured: true,
    title: "Domestic Helper Mary Jane Escalante on Keeping Hong Kong’s Mountains and Beaches Clean",
    titleZh: "【老外眼中的香港郊野】專訪外傭Mary Jane Escalante 愛上行山不忘淨山淨灘",
    excerpt: "Text: Fiona Leung (Former features reporter) Photography: Mary Jane Escalante Many people took up hiking during the COVID-19 pandemic, and domestic helpers were no exception. Mary Jane Escalante (Jane), who came to Hong Kong from the Philippines 20 years ago, had never tried hiki",
    excerptZh: "文：梁慧琳（前副刊專題記者）圖：Mary Jane Escalante 很多人在新冠疫情期間愛上行山，外傭也不例外。Mary Jane Escalante（Jane）20年前從菲律賓來港，之前在家鄉從未試過行山的她，發現了香港之美，展開在香港的自然之旅，改變她的人生。除了享受自然之美，她亦十分愛護大自然，上山下海時不忘淨山及淨灘。 採訪當天，Jane雖然不是穿運動裝，但她坐下來仍散發無窮活力，沒想過她已近50歲。原以為她年輕時已鍛鍊出運動細胞，誰知她在菲律賓從未行山，也沒有運動習慣，直至在2020年1月才與山結緣。她興高采烈地說：「政府呼籲外傭在休息日盡",
    date: "2026-07-30",
    author: "bonnie",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/07/PHOTO-2025-10-02-07-59-43-1-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/8773",
    urlZh: "https://blog.trailwatch.hk/zh/archives/8769",
    tags: [{ id: "conservation", name: "conservation", nameZh: "保育" }, { id: "interview", name: "interview", nameZh: "專訪" }, { id: "community", name: "community", nameZh: "社群" }],
  },
  {
    id: "blog-8763",
    sourceId: 8763,
    category: "features",
    title: "HK4TUC Finisher Tom Robertshaw on Trail Racing as Meditation and Self-Reflection",
    titleZh: "【老外眼中的香港郊野】專訪四徑完成者Tom Robertshaw 視山賽為冥想和自省之旅",
    excerpt: "Text: Cheng Mei Chi (Media Veteran) The documentary ‘Four Trails’ was released in Hong Kong in late 2024, striking a chord with seasoned and casual hikers alike. Tom Robertshaw appeared in the documentary. What is less know is that in 2017, Tom became the first Hong Kong Four Tra",
    excerptZh: "文：鄭美姿（資深傳媒工作者） 《香港四徑大步走》紀錄片於2024年尾在香港上映，在山系人非山系人、運動人非運動人之間，都取得很大的共鳴和回響。Tom Robertshaw亦曾在紀錄片中現身，有所不知的是，於2017年，他是第一位打破大會紀錄以少於60小時完賽（53小時）的四徑參與者。當人人都驚嘆於298公里的距離有幾長時，Tom卻直言，跑四徑的重點不是你跑得有幾遠，而是你在旅程當中，把自己挖掘得有幾深。 Tom是英國人，2009年來港9個月後，對此地一見鍾情。他說，在英國的Tom討厭跑步，更莫說跑山，但他喜歡旅遊，早於18歲中學一畢業，他便設計了一個孭背",
    date: "2026-07-30",
    author: "bonnie",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/07/cover-1-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/8763",
    urlZh: "https://blog.trailwatch.hk/zh/archives/8742",
    tags: [{ id: "events", name: "events", nameZh: "活動" }, { id: "trail-running", name: "trail running", nameZh: "越野跑" }, { id: "interview", name: "interview", nameZh: "專訪" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-1529",
    sourceId: 1529,
    category: "hiking-tips",
    title: "【Myths of Mountains】 How to Stay Chill on Trails (+ 3 Shady Routes Recommendation)",
    titleZh: "【行山迷思】炎炎夏日 係咪唔可以行山？附夏日短途行山路線推介",
    excerpt: "There is a lot to pay attention to when hiking in summer, not only on the preparation of equipment, but also special route planning is needed. A few routes suitable for hot summer days is recommended for this issue.",
    excerptZh: "夏天行山需要注意的事項相對較多，在行程計劃及裝備上都應加倍準備。TrailWatch推介三段適合夏天慢行、短程而且沿路有林蔭路徑的路線給各位山友參考。",
    date: "2026-06-30",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/01/201907_newsletter_cover_01b-1-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/1529",
    urlZh: "https://blog.trailwatch.hk/zh/archives/1524",
    tags: [{ id: "safety", name: "safety", nameZh: "安全" }, { id: "summer", name: "summer hiking", nameZh: "夏日行山" }, { id: "weather", name: "weather", nameZh: "天氣" }, { id: "gear", name: "gear", nameZh: "裝備" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-1496",
    sourceId: 1496,
    category: "hiking-tips",
    title: "【Myths of Mountain】How to Handle Thunderstorms While Hiking in Summer?",
    titleZh: "【行山迷思】夏日行山遇雷暴，留喺「邊樹」安全啲？",
    excerpt: "When hiking in summer, the weather can turn from sunny to stormy in minutes. How should prepare for hiking in summer? What should do if we encounter thunderstorm during a hike?",
    excerptZh: "【行山迷思】行山遇雷暴，留喺「邊樹」安全啲? 夏天的天氣變化很大，可以由晴朗的天氣一瞬間變為雷電交加，活動前應該要怎樣準備？若進行行山活動時才遇上雷暴，又應如何應變？",
    date: "2026-06-27",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/01/201906_newsletter_cover_02-1-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/1496",
    urlZh: "https://blog.trailwatch.hk/zh/archives/1493",
    tags: [{ id: "safety", name: "safety", nameZh: "安全" }, { id: "summer", name: "summer hiking", nameZh: "夏日行山" }, { id: "weather", name: "weather", nameZh: "天氣" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-8081",
    sourceId: 8081,
    category: "activity-review",
    title: "Backyard Life · Duckling Journal Trial Play Day Review",
    titleZh: "【後山生活・鴨遊記】將軍澳鴨仔山試玩日活動回顧",
    excerpt: "On 24 May (Sunday), we co-organised the Backyard Life · Duckling Journal Trial Play Day in collaboration with the Vocational Training Council (VTC) and CityUnseen. Duckling Hill backyard trail in Tseung Kwan O is a trail with a unique character. As it is situated near several pub",
    excerptZh: "5月24日（星期日），我們與職業訓練局（VTC）及香港建解（CityUnseen）合辦了【後山生活・鴨遊記】屋企後山試玩日。將軍澳鴨仔山是一條極具特色的山徑，鄰近將軍澳坑口多個屋苑，因而成為附近居民日常休憩與運動的熱門地點。正因如此，山徑內蘊藏了不少居民自發搭建的設施，以及展現其生活痕跡的物品。我們希望透過導賞團及任務形式的活動，讓參加者更深入認識鴨仔山，了解它與周邊地方的連結，並發掘山上獨特的設施與景色，從而令大家更懂得珍惜香港的後山小徑。 是次活動共吸引十多位青少年及附近居民參與。參加者不僅加深了對鴨仔山歷史的認識，也體會到行山除了常規的運動方式外，",
    date: "2026-06-25",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/06/1-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/8081",
    urlZh: "https://blog.trailwatch.hk/zh/archives/8050",
    tags: [{ id: "events", name: "events", nameZh: "活動" }, { id: "weather", name: "weather", nameZh: "天氣" }, { id: "backyard", name: "backyard trails", nameZh: "後園徑" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-8070",
    sourceId: 8070,
    category: "features",
    featured: true,
    title: "Trails for All: Hiking with Wheelchair Users",
    titleZh: "無障礙郊遊體驗 輪椅使用者重拾自然樂趣",
    excerpt: "Mr. and Mrs. Chu live in Ma On Shan, and while the country park is right near their home, they hesitated to visit. As they are both wheelchair users, hiking has never been easy or relaxing. “If it weren’t for our daughter and son-in-law, we would never have thought of visiting a ",
    excerptZh: "朱生和朱太家住馬鞍山，馬鞍山郊野公園近在眼前，卻總感到遙不可及。他倆都是輪椅使用者，郊遊從來都不是容易或輕鬆的事。 「如果不是女兒和女婿幫助我們，我們完全不會想去行郊野公園或者家樂徑。」朱生無奈說。有次，女兒、女婿嘗試帶他們行馬鞍山家樂徑。這條熱門的入門級山徑全長約半公里，需時約半小時，適合一家大小及初行山人士，可飽覽沙田、馬鞍山至大埔的景色。可是，山徑梯級密集，平時用的手動輪椅根本過不了，他倆只能改用拐杖，在家人攙扶下慢慢行，「所用時間比一般人多7、8倍，很吃力。」朱生描述當時情形。 常言香港的城市與山野就在「咫尺之間」；然而，這「咫尺之隔」，對輪椅使",
    date: "2026-06-25",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2022/06/cover-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/8070",
    urlZh: "https://blog.trailwatch.hk/zh/archives/8035",
    tags: [{ id: "accessible", name: "accessible hiking", nameZh: "無障礙" }, { id: "events", name: "events", nameZh: "活動" }, { id: "weather", name: "weather", nameZh: "天氣" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-1569",
    sourceId: 1569,
    category: "hiking-tips",
    title: "【Myths of Mountains】Feeling Sick When Hiking: Heat Exhaustion or Heat Stroke?(+3 Reservoir Routes Recommendation)",
    titleZh: "【行山迷思】行山唔舒服 究竟點分中暑定熱衰竭？附夏日水塘路線推介",
    excerpt: "What should you do when you have heat exhaustion or heat stroke in hot summer? We discuss this month the differences between the two and the ways to prevent it. We are also recommending three routes around the reservoirs for everyone to enjoy hiking in summer.",
    excerptZh: "夏天行山行到中途不適，應如何處理？是次TrailWatch推介炎夏適宜，三條平坦易行的水塘路徑，希望大家可以享受夏天的行山樂趣。",
    date: "2026-06-15",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/01/201908_newsletter_cover_02-1-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/1569",
    urlZh: "https://blog.trailwatch.hk/zh/archives/1563",
    tags: [{ id: "safety", name: "safety", nameZh: "安全" }, { id: "summer", name: "summer hiking", nameZh: "夏日行山" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-2188",
    sourceId: 2188,
    category: "hiking-tips",
    title: "Hiking in Hot Weather: How to Prevent Heat-related illnesses",
    titleZh: "夏日郊遊安全小貼士（下）：炎夏行山途中，如何避免不適？",
    excerpt: "Tips and Tools to maximise your hiking experience in Hong Kong.",
    excerptZh: "上回提到夏日郊遊出發前的準備，今次分享一下在炎熱天氣下郊遊需注意的事項：",
    date: "2026-06-15",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/01/2020_0608_FB_01-1-768x768.jpg",
    url: "https://blog.trailwatch.hk/archives/2188",
    urlZh: "https://blog.trailwatch.hk/zh/archives/2185",
    tags: [{ id: "safety", name: "safety", nameZh: "安全" }, { id: "summer", name: "summer hiking", nameZh: "夏日行山" }, { id: "weather", name: "weather", nameZh: "天氣" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-2174",
    sourceId: 2174,
    category: "hiking-tips",
    title: "Hiking in Hot Weather: How to Plan Your Trip and Pack Your Bag",
    titleZh: "夏日郊遊安全小貼士 （上）：炎夏郊遊出發前的準備",
    excerpt: "Tips and Tools to maximise your hiking experience in Hong Kong.",
    excerptZh: "如果大家想在炎熱天氣下行山，就要注意以下幾個安全貼士了",
    date: "2026-05-28",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/01/2020_0519_FB_01-01-1-768x768.jpg",
    url: "https://blog.trailwatch.hk/archives/2174",
    urlZh: "https://blog.trailwatch.hk/zh/archives/2171",
    tags: [{ id: "safety", name: "safety", nameZh: "安全" }, { id: "summer", name: "summer hiking", nameZh: "夏日行山" }, { id: "weather", name: "weather", nameZh: "天氣" }, { id: "gear", name: "gear", nameZh: "裝備" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-7238",
    sourceId: 7238,
    category: "activity-review",
    title: "Hong Kong Island Coastal Trail Challenge 2025/26 Closing & Award Ceremony",
    titleZh: "香港島環島徑挑戰2025/26 閉幕暨頒獎典禮",
    excerpt: "Hong Kong Island Coastal Trail Challenge 2025/26 Closing & Award Ceremony was successfully held at Museum Cafe8!",
    excerptZh: "香港島環島徑挑戰2025/26閉幕暨頒獎典禮，已於Museum Cafe8順利舉行。",
    date: "2026-02-20",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/03/DSC_1679-1-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/7238",
    urlZh: "https://blog.trailwatch.hk/zh/archives/7230",
    tags: [{ id: "events", name: "events", nameZh: "活動" }, { id: "hk-island", name: "Hong Kong Island", nameZh: "香港島" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-7211",
    sourceId: 7211,
    category: "features",
    title: "Trails in Transition",
    titleZh: "變化中的路線",
    excerpt: "Each time we tread the hiking trails, the routes, trail conditions, and scenery change. For those familiar with nature, you may even be able to catch a glimpse of the traces of change over time.",
    excerptZh: "「路係人行出嚟嘅。」走着走着，路線、路況與景觀也有轉變。熟悉山路者，或許可以邊走邊察覺到時移勢易的痕跡。",
    date: "2026-02-20",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/03/%E7%B4%85%E8%8A%B1%E5%B6%BA1_20251125_151932-1-768x576.jpg",
    url: "https://blog.trailwatch.hk/archives/7211",
    urlZh: "https://blog.trailwatch.hk/zh/archives/7222",
    tags: [{ id: "trails", name: "trails", nameZh: "徑道" }, { id: "interview", name: "interview", nameZh: "專訪" }],
  },
  {
    id: "blog-7189",
    sourceId: 7189,
    category: "whats-new",
    featured: true,
    title: "TrailWatch Revamp Upgrade Announcement",
    titleZh: "TrailWatch 更新：新版本面世通知",
    excerpt: "Our team is currently working with our developer on a range of updates to the website and app.",
    excerptZh: "TrailWatch 團隊正與開發人員合作，為網站及應用程式進行一系列更新。",
    date: "2025-12-30",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/03/TrailWatch-%E6%9B%B4%E6%96%B0%EF%BC%9A%E6%96%B0%E7%89%88%E9%9D%A2%E9%9D%A2%E4%B8%96%E9%80%9A%E7%9F%A5-TrailWatch-Revamp-Upgrade-Announcement-1-1-768x284.png",
    url: "https://blog.trailwatch.hk/archives/7189",
    urlZh: "https://blog.trailwatch.hk/zh/archives/7187",
    tags: [{ id: "app", name: "app", nameZh: "應用程式" }, { id: "community", name: "community", nameZh: "社群" }],
  },
  {
    id: "blog-7185",
    sourceId: 7185,
    category: "activity-review",
    title: "Nature and Technology: Accessible Hiking Workshop (Session 5) Event Recap",
    titleZh: "「無障礙郊遊工作坊（第五節）」活動回顧",
    excerpt: "Sponsored by “Operation Santa Claus,” the fifth Accessible Hiking Workshop was successfully held on 22 October 2025. Despite a sudden cold snap before the event, it still attracted two wheelchair users, 12 elderly participants, and 16 volunteers from Hong Kong Baptist University.",
    excerptZh: "由「愛心聖誕大行動」捐助的「無障礙郊遊工作坊」第五節已於2025年10月22日在東蒲順利舉行。儘管活動前夕前天氣急速變冷，活動仍吸引2位輪椅使用者、12位長者，以及16位來自浸會大學嘅義工出席活動。",
    date: "2025-11-17",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/03/Acc202511_01-1-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/7185",
    urlZh: "https://blog.trailwatch.hk/zh/archives/7178",
    tags: [{ id: "accessible", name: "accessible hiking", nameZh: "無障礙" }, { id: "events", name: "events", nameZh: "活動" }, { id: "weather", name: "weather", nameZh: "天氣" }],
  },
  {
    id: "blog-7171",
    sourceId: 7171,
    category: "features",
    title: "Hear Us Out: This is What Hiking Safety is All About",
    titleZh: "收到收唔到 行山安全要知道",
    excerpt: "As the weather cools and hiking season begins, more hikers are heading to the mountains. In 2024, the Fire Services Department responded to 588 mountain rescue incidents, which resulted in 345 people injured and 15 fatalities. Although these numbers show a slight decrease compare",
    excerptZh: "隨着天氣漸涼、行山季開始，山上的行山客漸多。2024年，消防處接獲588宗攀山救援事故，其中有345人受傷，15人意外身亡。儘管數字相比2022及2023年稍有下降，但依然可觀。行山必須注意安全，在此簡介數項注意事項。最後為大家介紹三條路線，希望大家可以安全地享受今個行山季！",
    date: "2025-11-17",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/03/FS_202511_01-1-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/7171",
    urlZh: "https://blog.trailwatch.hk/zh/archives/7154",
    tags: [{ id: "safety", name: "safety", nameZh: "安全" }, { id: "weather", name: "weather", nameZh: "天氣" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-7137",
    sourceId: 7137,
    category: "activity-review",
    title: "Nature and Technology: Accessible Hiking Workshop (Session 3 and 4) Event Recap",
    titleZh: "「無障礙郊遊工作坊（第三及四節）」圓滿結束 探索自然無界限",
    excerpt: "Sponsored by “Operation Santa Claus,” the third and fourth session of the Accessible Hiking Workshops were successfully held on July 17 and August 13, 2025, respectively. The two sessions attracted a total of 8 wheelchair users and 52 elderly participants to explore the joys and ",
    excerptZh: "由「愛心聖誕大行動」捐助的「無障礙郊遊工作坊」第三及四節已分別於2025年7月17日及8月13日在東蒲順利舉行。兩節活動共吸引8位輪椅使用者及52位長者參與，一同探索無障礙郊遊的樂趣與可能性。",
    date: "2025-08-19",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/03/WC_202508_01-1-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/7137",
    urlZh: "https://blog.trailwatch.hk/zh/archives/7130",
    tags: [{ id: "accessible", name: "accessible hiking", nameZh: "無障礙" }, { id: "events", name: "events", nameZh: "活動" }],
  },
  {
    id: "blog-7123",
    sourceId: 7123,
    category: "features",
    title: "Train in Nature: 3 Outdoor Gyms to Improve Fitness",
    titleZh: "邊行山邊健身：户外健身室三選",
    excerpt: "Heroes in martial arts novels often retreat to mountains to train, and subsequently emerge with extraordinary skills. But did you know, countryside locations for physical training not only exist in the fictional world, but can also be found in Hong Kong’s nature? Here, TrailWatch",
    excerptZh: "讀武俠小説時常見英雄人物歸隱深山修煉武功，練成驚為天人的獨門秘技。但你又是否知道香港的郊野中也有修身健體之所？TrailWatch 為大家推介三條郊野健身路線，並邀請到來自瑞典的健身導師兼業餘應用程式設計師 Demir Bircan 指導。",
    date: "2025-08-19",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/03/FS_202508_01-1-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/7123",
    urlZh: "https://blog.trailwatch.hk/zh/archives/7106",
    tags: [{ id: "app", name: "app", nameZh: "應用程式" }, { id: "fitness", name: "fitness", nameZh: "健身" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-7089",
    sourceId: 7089,
    category: "features",
    featured: true,
    title: "What We Can Learn From a Decade of Hiking Records",
    titleZh: "十年行山數據之觀察",
    excerpt: "In the past ten years, our 200,000+ TrailWatch users recorded over 1 million activities. Recorded routes were over 1.2 million kilometers long, and activity records totalled over 7.5 million hours. TrailWatch’s tenth anniversary is the perfect chance for us to take a look at all ",
    excerptZh: "十年以來，超過20萬名TrailWatch用户一共記錄了逾100萬項活動，路線總長接近120萬公里，活動記錄合共超過750萬小時。藉着十週年的機會，我們分析了十年來的活動記錄，看看香港行山風氣的變化。",
    date: "2025-06-24",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/03/TW-202506_Cover_logo-1-768x432.jpg",
    url: "https://blog.trailwatch.hk/archives/7089",
    urlZh: "https://blog.trailwatch.hk/zh/archives/7082",
    tags: [{ id: "trails", name: "trails", nameZh: "徑道" }, { id: "data", name: "data insights", nameZh: "數據洞察" }],
  },
  {
    id: "blog-7068",
    sourceId: 7068,
    category: "blog",
    title: "Findings from the TrailWatch Newsletter Reader Survey",
    titleZh: "TrailWatch 通訊讀者問卷結果統計",
    excerpt: "We reached out to our users this April and May through our social media and e-newsletter to invite them to fill out an anonymous survey, in order to learn more about each user, and better understand users’ hiking habits and the issues regarding country parks and trails they are c",
    excerptZh: "我們於今年4至5月間透過社交媒體及電郵通訊邀請讀者填寫不記名問卷，了解用户的遠足習慣及關注的郊野議題。",
    date: "2025-06-17",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/03/TW-survey-newsletter-graphic-768x576.png",
    url: "https://blog.trailwatch.hk/archives/7068",
    urlZh: "https://blog.trailwatch.hk/zh/archives/7074",
    tags: [{ id: "community", name: "community", nameZh: "社群" }, { id: "trails", name: "trails", nameZh: "徑道" }],
  },
  {
    id: "blog-7062",
    sourceId: 7062,
    category: "activity-review",
    title: "Accessible Hiking Workshop (Session 2) Event Recap",
    titleZh: "「無障礙郊遊工作坊（第二節）」圓滿結束 攜手共創包容戶外體驗",
    excerpt: "Sponsored by “Operation Santa Claus,” the 2nd session of the Accessible Hiking Workshop was successfully held on 16 May at Tung Po. The event brought together 6 wheelchair users, over 10 elderly participants, and 20 student volunteers from Hong Kong Baptist University to explore ",
    excerptZh: "由「愛心聖誕大行動」捐助的無障礙郊遊工作坊（第二節）已於2025年5月16日在東蒲順利舉行。本次活動共吸引六位輪椅使用者、十多位長者，以及二十位香港浸會大學學生義工共同參與，攜手探索無障礙郊遊的樂趣與可能性。",
    date: "2025-06-17",
    author: "admin",
    image: "https://blog.trailwatch.hk/wp-content/uploads/2026/03/202506_acc_01-1-768x512.jpg",
    url: "https://blog.trailwatch.hk/archives/7062",
    urlZh: "https://blog.trailwatch.hk/zh/archives/7055",
    tags: [{ id: "accessible", name: "accessible hiking", nameZh: "無障礙" }, { id: "events", name: "events", nameZh: "活動" }],
  },
];

TW.articleCategoryLabel = function (categoryId) {
  const key = ({
    all: "article_cat_all",
    blog: "article_cat_blog",
    features: "article_cat_features",
    "hiking-tips": "article_cat_hiking_tips",
    "activity-review": "article_cat_activity_review",
    "whats-new": "article_cat_whats_new",
  })[categoryId];
  return key ? TW.t(key) : categoryId;
};

TW.articleDateValue = function (a) {
  const raw = (a && a.date) || "";
  const t = Date.parse(raw);
  return Number.isFinite(t) ? t : 0;
};

TW.getArticles = function (opts) {
  opts = opts || {};
  const cat = opts.category || "all";
  const q = (opts.query || "").trim().toLowerCase();
  const sort = opts.sort === "oldest" ? "oldest" : "newest";
  const zh = TW.getLang && TW.getLang() === "zh";
  let list = (TW.articles || []).filter((a) => {
    if (opts.featured && !a.featured) return false;
    if (cat && cat !== "all" && a.category !== cat) return false;
    if (!q) return true;
    const title = zh ? a.titleZh : a.title;
    const excerpt = zh ? a.excerptZh : a.excerpt;
    const tags = (a.tags || []).map((t) => (zh ? t.nameZh : t.name)).join(" ");
    const blob = [title, excerpt, tags, a.author, a.category].join(" ").toLowerCase();
    return blob.includes(q);
  });
  list = list.slice().sort((a, b) => {
    const da = TW.articleDateValue(a);
    const db = TW.articleDateValue(b);
    return sort === "oldest" ? da - db : db - da;
  });
  return list;
};

TW.getFeaturedArticles = function () {
  return TW.getArticles({ featured: true, sort: "newest" });
};

TW.hkCenter = [22.3193, 114.1694];

/** Demo friends for invites (website) */
TW.demoFriends = [
  {
    id: "friend_elena",
    name: "Elena Green",
    email: "elena@example.com",
    rank: "Rare Hiker Level 3",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
  },
  {
    id: "friend_marcus",
    name: "Marcus Lee",
    email: "marcus@example.com",
    rank: "Trail Friend Level 2",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
  },
  {
    id: "friend_sarah",
    name: "Sarah Chen",
    email: "sarah@example.com",
    rank: "Weekend Walker",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
  },
];

TW.getPlans = function () {
  try {
    return JSON.parse(localStorage.getItem("tw_plans") || "[]");
  } catch (e) {
    return [];
  }
};

TW.setPlans = function (ids) {
  localStorage.setItem("tw_plans", JSON.stringify(ids));
};

TW.togglePlan = function (trailId) {
  const plans = TW.getPlans();
  const i = plans.indexOf(trailId);
  if (i >= 0) {
    plans.splice(i, 1);
    TW.setPlans(plans);
    return false;
  }
  plans.push(trailId);
  TW.setPlans(plans);
  return true;
};

TW.isPlanned = function (trailId) {
  return TW.getPlans().indexOf(trailId) >= 0;
};

TW.districtName = function (id) {
  const d = TW.districts.find((x) => x.id === id);
  if (!d) return id;
  return TW.getLang() === "zh" ? d.nameZh : d.name;
};
